//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPermission_Functions
    {
        public int Id { get; set; }
        public Nullable<int> PermissionId { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string AccessRightIds { get; set; }
        public Nullable<bool> MyIfnfoOnly { get; set; }
    
        public virtual Adminpermission Adminpermission { get; set; }
        public virtual LicensedFunction LicensedFunction { get; set; }
    }
}
