//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_AgencyList
    {
        public Config_AgencyList()
        {
            this.Config_TeamList = new HashSet<Config_TeamList>();
            this.UserDataScopes = new HashSet<UserDataScope>();
            this.Dom_DomainBasic = new HashSet<Dom_DomainBasic>();
        }
    
        public int AgencyID { get; set; }
        public string AgencyTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Config_TeamList> Config_TeamList { get; set; }
        public virtual ICollection<UserDataScope> UserDataScopes { get; set; }
        public virtual ICollection<Dom_DomainBasic> Dom_DomainBasic { get; set; }
    }
}
