//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_MembersList
    {
        public Config_MembersList()
        {
            this.Dom_AssignDomainToMembers = new HashSet<Dom_AssignDomainToMembers>();
            this.PCR_PCRHistory = new HashSet<PCR_PCRHistory>();
        }
    
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Dom_AssignDomainToMembers> Dom_AssignDomainToMembers { get; set; }
        public virtual ICollection<PCR_PCRHistory> PCR_PCRHistory { get; set; }
    }
}
