//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCR_DomainList
    {
        public int ID { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> DCR_SchemaId { get; set; }
        public string DomainName { get; set; }
        public Nullable<bool> SkipFirstRow { get; set; }
    }
}
