//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCR_Schema_ColumnsList
    {
        public DCR_Schema_ColumnsList()
        {
            this.DCR_Schema_Details = new HashSet<DCR_Schema_Details>();
        }
    
        public int ColumnID { get; set; }
        public string ColumnName { get; set; }
        public string ColumnType { get; set; }
        public Nullable<bool> IsDeletable { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    
        public virtual ICollection<DCR_Schema_Details> DCR_Schema_Details { get; set; }
    }
}
