//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCR_PTPType
    {
        public PCR_PTPType()
        {
            this.PCR_PCRHistory = new HashSet<PCR_PCRHistory>();
        }
    
        public byte PTPTypeID { get; set; }
        public string PTPTypeTitle { get; set; }
    
        public virtual ICollection<PCR_PCRHistory> PCR_PCRHistory { get; set; }
    }
}
