//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Config
    {
        public short RecordID { get; set; }
        public string FiledTitle { get; set; }
        public string FieldText { get; set; }
        public byte[] FieldImage { get; set; }
        public Nullable<System.DateTime> FieldDate { get; set; }
    }
}
