//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_FormList
    {
        public Pre_FormList()
        {
            this.Pre_GroupPermissions = new HashSet<Pre_GroupPermissions>();
            this.Pre_ModuleForms = new HashSet<Pre_ModuleForms>();
            this.Pre_Trans_Log = new HashSet<Pre_Trans_Log>();
        }
    
        public short FormID { get; set; }
        public string CodeName { get; set; }
        public string FormTitle { get; set; }
        public bool IsActive { get; set; }
        public bool GetInNotifications { get; set; }
        public string TrackViewName { get; set; }
        public string KeyFieldName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCBy { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
    
        public virtual ICollection<Pre_GroupPermissions> Pre_GroupPermissions { get; set; }
        public virtual ICollection<Pre_ModuleForms> Pre_ModuleForms { get; set; }
        public virtual ICollection<Pre_Trans_Log> Pre_Trans_Log { get; set; }
    }
}
