//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCR_Schema_VIEW
    {
        public int DCR_Schema_ID { get; set; }
        public string DCR_Schema_Name { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public string BranchName { get; set; }
        public int ID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<int> SchemaID { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public string ColumnName { get; set; }
    }
}
