//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lup_MonthYear
    {
        public Lup_MonthYear()
        {
            this.Dom_DomainBasic = new HashSet<Dom_DomainBasic>();
        }
    
        public int MonthID { get; set; }
        public string MonthYear { get; set; }
    
        public virtual ICollection<Dom_DomainBasic> Dom_DomainBasic { get; set; }
    }
}
