//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Section
    {
        public Pre_Section()
        {
            this.LicensedFunctions = new HashSet<LicensedFunction>();
        }
    
        public byte SectionID { get; set; }
        public string SectionName { get; set; }
        public string SectionURL { get; set; }
    
        public virtual ICollection<LicensedFunction> LicensedFunctions { get; set; }
    }
}
