//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminpermission
    {
        public Adminpermission()
        {
            this.AdminPermission_Functions = new HashSet<AdminPermission_Functions>();
        }
    
        public int premissionid { get; set; }
        public Nullable<int> domaintypeid { get; set; }
        public Nullable<int> domaindataid { get; set; }
        public string portalaccessids { get; set; }
    
        public virtual Adminpermission Adminpermissions1 { get; set; }
        public virtual Adminpermission Adminpermission1 { get; set; }
        public virtual DomainType DomainType { get; set; }
        public virtual ICollection<AdminPermission_Functions> AdminPermission_Functions { get; set; }
    }
}
