//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrt_Contacts
    {
        public int AgencyID { get; set; }
        public byte BranchID { get; set; }
        public string ConnectionTypeTitle { get; set; }
        public Nullable<int> ContactCount { get; set; }
    }
}
