//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dom_AssignDomainToMembers
    {
        public long AssignID { get; set; }
        public long AccountID { get; set; }
        public int MemberID { get; set; }
        public short RoleID { get; set; }
        public int TeamID { get; set; }
        public Nullable<bool> IsBank { get; set; }
    
        public virtual Config_TeamList Config_TeamList { get; set; }
        public virtual Dom_DomainsDataExtra Dom_DomainsDataExtra { get; set; }
        public virtual Lup_TeamRole Lup_TeamRole { get; set; }
        public virtual Config_MembersList Config_MembersList { get; set; }
    }
}
