//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dom_AssignDomainToMembersList
    {
        public string AssignedTo { get; set; }
        public string RoleName { get; set; }
        public string TeamName { get; set; }
        public string MemberName { get; set; }
        public long AssignID { get; set; }
        public long AccountID { get; set; }
        public int MemberID { get; set; }
        public short RoleID { get; set; }
        public int TeamID { get; set; }
        public Nullable<bool> IsBank { get; set; }
    }
}
