//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Users
    {
        public Pre_Users()
        {
            this.Pre_BranchesPermissions = new HashSet<Pre_BranchesPermissions>();
            this.Pre_GroupsMembers = new HashSet<Pre_GroupsMembers>();
            this.Pre_Trans_Log = new HashSet<Pre_Trans_Log>();
            this.Pre_UserStatus = new HashSet<Pre_UserStatus>();
            this.UserDataScopes = new HashSet<UserDataScope>();
        }
    
        public short UserID { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public bool IsActive { get; set; }
        public byte[] ProfileImage { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCBy { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
        public string BranchIDs { get; set; }
        public string BankIDs { get; set; }
        public string ProductIDs { get; set; }
        public string TypeIDs { get; set; }
        public string RegionIDs { get; set; }
    
        public virtual ICollection<Pre_BranchesPermissions> Pre_BranchesPermissions { get; set; }
        public virtual ICollection<Pre_GroupsMembers> Pre_GroupsMembers { get; set; }
        public virtual ICollection<Pre_Trans_Log> Pre_Trans_Log { get; set; }
        public virtual ICollection<Pre_UserStatus> Pre_UserStatus { get; set; }
        public virtual ICollection<UserDataScope> UserDataScopes { get; set; }
    }
}
