//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_BranchesPermissions
    {
        public short RecordID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<short> UserID { get; set; }
    
        public virtual Lup_BranchList Lup_BranchList { get; set; }
        public virtual Pre_Users Pre_Users { get; set; }
    }
}
