//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Domain_Region = new HashSet<Domain_Region>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<Domain_Region> Domain_Region { get; set; }
    }
}
