//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_SchemaColumns
    {
        public int RecoredSerial { get; set; }
        public byte CoID { get; set; }
        public byte SchemaID { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
    
        public virtual Sch_Columns Sch_Columns { get; set; }
        public virtual Sch_Schemas Sch_Schemas { get; set; }
    }
}
