//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_SchemaColList
    {
        public byte SchemaID { get; set; }
        public string SchemaName { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public byte CoID { get; set; }
        public int RecoredSerial { get; set; }
        public byte Expr1 { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public string ColumnName { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public string ColumnType { get; set; }
    }
}
