//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dom_AccountsPayments
    {
        public long PaymentID { get; set; }
        public long RecordSerial { get; set; }
        public Nullable<decimal> PaymentValue { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<long> DomainID { get; set; }
    
        public virtual Dom_DomainsDataExtra Dom_DomainsDataExtra { get; set; }
    }
}
