//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain_DataScope
    {
        public long DomainID { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public int AgencyID { get; set; }
        public int MonthID { get; set; }
        public byte BranchID { get; set; }
        public string DomainTitle { get; set; }
        public string DomainType { get; set; }
        public Nullable<bool> SuccessDomain { get; set; }
        public Nullable<bool> ISHIDEN { get; set; }
        public Nullable<int> SchemaId { get; set; }
        public string SchemaName { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public int DomainTypeID { get; set; }
        public int ProductID { get; set; }
        public int RegionID { get; set; }
    }
}
