//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_Schemas
    {
        public Sch_Schemas()
        {
            this.Sch_SchemaColumns = new HashSet<Sch_SchemaColumns>();
            this.Dom_DomainsDataExtra = new HashSet<Dom_DomainsDataExtra>();
        }
    
        public byte SchemaID { get; set; }
        public string SchemaName { get; set; }
        public Nullable<byte> BranchID { get; set; }
    
        public virtual Lup_BranchList Lup_BranchList { get; set; }
        public virtual ICollection<Sch_SchemaColumns> Sch_SchemaColumns { get; set; }
        public virtual ICollection<Dom_DomainsDataExtra> Dom_DomainsDataExtra { get; set; }
    }
}
