//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_Columns
    {
        public Sch_Columns()
        {
            this.Sch_SchemaColumns = new HashSet<Sch_SchemaColumns>();
        }
    
        public byte CoID { get; set; }
        public string ColumnName { get; set; }
        public string ColumnType { get; set; }
        public Nullable<bool> IsDeleteable { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    
        public virtual ICollection<Sch_SchemaColumns> Sch_SchemaColumns { get; set; }
    }
}
