//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.UserDataScopes = new HashSet<UserDataScope>();
            this.Domain_DomainType = new HashSet<Domain_DomainType>();
        }
    
        public int DomainId { get; set; }
        public string DomainName { get; set; }
    
        public virtual ICollection<UserDataScope> UserDataScopes { get; set; }
        public virtual ICollection<Domain_DomainType> Domain_DomainType { get; set; }
    }
}
