//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lup_TeamRole
    {
        public Lup_TeamRole()
        {
            this.Dom_AssignDomainToMembers = new HashSet<Dom_AssignDomainToMembers>();
        }
    
        public short RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Dom_AssignDomainToMembers> Dom_AssignDomainToMembers { get; set; }
    }
}
