//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Actions
    {
        public Pre_Actions()
        {
            this.Pre_GroupPermissions = new HashSet<Pre_GroupPermissions>();
            this.Pre_Trans_Log = new HashSet<Pre_Trans_Log>();
        }
    
        public byte ActionID { get; set; }
        public string ActionTitle { get; set; }
        public bool IsGlobal { get; set; }
        public bool OnlyLogAction { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCBy { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
    
        public virtual ICollection<Pre_GroupPermissions> Pre_GroupPermissions { get; set; }
        public virtual ICollection<Pre_Trans_Log> Pre_Trans_Log { get; set; }
    }
}
