//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Offices1
    {
        public Pre_Offices1()
        {
            this.Pre_OfficesMembers = new HashSet<Pre_OfficesMembers>();
        }
    
        public byte OfficeId { get; set; }
        public string OfficeTitle { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCByD { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
    
        public virtual ICollection<Pre_OfficesMembers> Pre_OfficesMembers { get; set; }
    }
}
