//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_SystemModules
    {
        public Pre_SystemModules()
        {
            this.Pre_ModuleForms = new HashSet<Pre_ModuleForms>();
        }
    
        public byte ModuleID { get; set; }
        public string ModuleTitle { get; set; }
        public byte DisplayOrder { get; set; }
        public bool IsHidden { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCBy { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
    
        public virtual ICollection<Pre_ModuleForms> Pre_ModuleForms { get; set; }
    }
}
