//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_FormActions
    {
        public short RecordSerial { get; set; }
        public short FormID { get; set; }
        public byte ActionID { get; set; }
        public bool IsNotificationAction { get; set; }
    }
}
