//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_UsersView
    {
        public short UserID { get; set; }
        public string DisplayName { get; set; }
        public string BranchIDs { get; set; }
        public Nullable<byte> GroupID { get; set; }
        public string SectionIDs { get; set; }
        public string UserName { get; set; }
        public byte[] ProfileImage { get; set; }
        public Nullable<byte> OfficeId { get; set; }
    }
}
