//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCR_Schema_Details
    {
        public int ID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<int> SchemaID { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
    
        public virtual DCR_Schema DCR_Schema { get; set; }
        public virtual DCR_Schema_ColumnsList DCR_Schema_ColumnsList { get; set; }
    }
}
