//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensedFunction
    {
        public LicensedFunction()
        {
            this.AdminPermission_Functions = new HashSet<AdminPermission_Functions>();
        }
    
        public int FinctionId { get; set; }
        public string FunctionName { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<byte> SectionPortalId { get; set; }
        public string ScreenGroup { get; set; }
        public string ScreenURL { get; set; }
    
        public virtual ICollection<AdminPermission_Functions> AdminPermission_Functions { get; set; }
        public virtual Pre_Section Pre_Section { get; set; }
    }
}
