//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Groups
    {
        public Pre_Groups()
        {
            this.Employees = new HashSet<Employee>();
            this.Pre_GroupPermissions = new HashSet<Pre_GroupPermissions>();
            this.Pre_GroupsMembers = new HashSet<Pre_GroupsMembers>();
        }
    
        public byte GroupID { get; set; }
        public string GroupTitle { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public Nullable<short> RCBy { get; set; }
        public Nullable<System.DateTime> LADate { get; set; }
        public Nullable<short> LABy { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Pre_GroupPermissions> Pre_GroupPermissions { get; set; }
        public virtual ICollection<Pre_GroupsMembers> Pre_GroupsMembers { get; set; }
    }
}
