//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.UserDataScopes = new HashSet<UserDataScope>();
            this.Domain_Product = new HashSet<Domain_Product>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<UserDataScope> UserDataScopes { get; set; }
        public virtual ICollection<Domain_Product> Domain_Product { get; set; }
    }
}
