//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDataScope
    {
        public int ID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string RegionID { get; set; }
        public Nullable<short> UserId { get; set; }
        public string CityID { get; set; }
    
        public virtual Config_AgencyList Config_AgencyList { get; set; }
        public virtual Pre_Users Pre_Users { get; set; }
        public virtual Product Product { get; set; }
        public virtual Type Type { get; set; }
    }
}
